//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: chatbox.cpp
//  Source: chatbox.idl
//  Generated: Mon Dec 26 22:38:08 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "chatbox.h"




